In [2]:
import pandas as pd
import numpy as np
import pickle
from sklearn.neighbors import DistanceMetric
from math import radians

In [2]:
stations = pd.read_csv('../data/stations_cleaned.csv.gz')

/Users/danielchoy/opt/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3063: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [7]:
ride_stations = pd.read_csv('../data/riders_cleaned.csv.gz', usecols = ['start station id', 'start station name', 'start station latitude', 'start station longitude'])

In [11]:
ride_stations

start station id          start station name  \
0                      3331     Riverside Dr & W 104 St   
1                      3101       N 12 St & Bedford Ave   
2                      3140             1 Ave & E 78 St   
3                       236         St Marks Pl & 2 Ave   
4                      3427    Lafayette St & Jersey St   
...                     ...                         ...   
110341608              3244      University Pl & E 8 St   
110341609               383  Greenwich Ave & Charles St   
110341610               150           E 2 St & Avenue C   
110341611               483             E 12 St & 3 Ave   
110341612               327    Vesey Pl & River Terrace   

           start station latitude  start station longitude  
0                       40.801343               -73.971146  
1                       40.720798               -73.954847  
2                       40.771404               -73.953517  
3                       40.728419               -73.987140  
4                       40.724305               -73.996010  
...                           ...                      ...  
110341608               40.731437               -73.994903  
110341609               40.735238               -74.000271  
110341610               40.720874               -73.980858  
110341611               40.732233               -73.988900  
110341612               40.715338               -74.016584  

[110341613 rows x 4 columns]

In [29]:
# Method 1
ride_stations_df = ride_stations.groupby('start station id')[['start station latitude', 'start station longitude']].mean().reset_index()

In [40]:
# Method 2
ride_stations_df = ride_stations.drop_duplicates(subset = ['start station id'])

In [41]:
ride_stations_df

start station id                   start station name  \
0                      3331              Riverside Dr & W 104 St   
1                      3101                N 12 St & Bedford Ave   
2                      3140                      1 Ave & E 78 St   
3                       236                  St Marks Pl & 2 Ave   
4                      3427             Lafayette St & Jersey St   
...                     ...                                  ...   
104429750              3252  Bike The Branches - Red Hook Branch   
106981303              3248                         LPI Facility   
107204017              3215                        JSQ Don't Use   
107204025              3480                         WS Don't Use   
107210640              3197                         Hs Don't Use   

           start station latitude  start station longitude  
0                       40.801343               -73.971146  
1                       40.720798               -73.954847  
2                       40.771404               -73.953517  
3                       40.728419               -73.987140  
4                       40.724305               -73.996010  
...                           ...                      ...  
104429750               40.675350               -74.010020  
106981303                0.000000                 0.000000  
107204017                0.000000                 0.000000  
107204025                0.000000                 0.000000  
107210640               40.719252               -74.034234  

[1360 rows x 4 columns]

In [42]:
ride_stations_df=ride_stations_df.rename(columns = {'start station id': 'dock_id'})

In [44]:
ride_stations_df = ride_stations_df.reset_index()

In [48]:
ride_stations_df = ride_stations_df.drop('index', axis = 1)

In [49]:
ride_stations_df

dock_id                   start station name  start station latitude  \
0        3331              Riverside Dr & W 104 St               40.801343   
1        3101                N 12 St & Bedford Ave               40.720798   
2        3140                      1 Ave & E 78 St               40.771404   
3         236                  St Marks Pl & 2 Ave               40.728419   
4        3427             Lafayette St & Jersey St               40.724305   
...       ...                                  ...                     ...   
1355     3252  Bike The Branches - Red Hook Branch               40.675350   
1356     3248                         LPI Facility                0.000000   
1357     3215                        JSQ Don't Use                0.000000   
1358     3480                         WS Don't Use                0.000000   
1359     3197                         Hs Don't Use               40.719252   

      start station longitude  
0                  -73.971146  
1                  -73.954847  
2                  -73.953517  
3                  -73.987140  
4                  -73.996010  
...                       ...  
1355               -74.010020  
1356                 0.000000  
1357                 0.000000  
1358                 0.000000  
1359               -74.034234  

[1360 rows x 4 columns]

In [50]:
# Convert the Lat/Long degress in Radians
ride_stations_df['lat'] = np.radians(ride_stations_df['start station latitude'])
ride_stations_df['long'] = np.radians(ride_stations_df['start station longitude'])

In [51]:
# Scipy get_metrics()
dist = DistanceMetric.get_metric('manhattan')

In [52]:
ride_stations_df[['lat','long']].to_numpy()

array([[ 0.71211778, -1.29104004],
       [ 0.710712  , -1.29075558],
       [ 0.71159524, -1.29073236],
       ...,
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.71068501, -1.29214114]])

In [53]:
dist.pairwise(ride_stations_df [['lat','long']].to_numpy())*6373

array([[0.00000000e+00, 1.07719213e+01, 5.29101229e+00, ...,
        1.27661248e+04, 1.27661248e+04, 1.61483401e+01],
       [1.07719213e+01, 0.00000000e+00, 5.77689602e+00, ...,
        1.27553529e+04, 1.27553529e+04, 9.00220524e+00],
       [5.29101229e+00, 5.77689602e+00, 0.00000000e+00, ...,
        1.27608338e+04, 1.27608338e+04, 1.47791013e+01],
       ...,
       [1.27661248e+04, 1.27553529e+04, 1.27608338e+04, ...,
        0.00000000e+00, 0.00000000e+00, 1.27640111e+04],
       [1.27661248e+04, 1.27553529e+04, 1.27608338e+04, ...,
        0.00000000e+00, 0.00000000e+00, 1.27640111e+04],
       [1.61483401e+01, 9.00220524e+00, 1.47791013e+01, ...,
        1.27640111e+04, 1.27640111e+04, 0.00000000e+00]])

In [54]:
ride_stations_df

dock_id                   start station name  start station latitude  \
0        3331              Riverside Dr & W 104 St               40.801343   
1        3101                N 12 St & Bedford Ave               40.720798   
2        3140                      1 Ave & E 78 St               40.771404   
3         236                  St Marks Pl & 2 Ave               40.728419   
4        3427             Lafayette St & Jersey St               40.724305   
...       ...                                  ...                     ...   
1355     3252  Bike The Branches - Red Hook Branch               40.675350   
1356     3248                         LPI Facility                0.000000   
1357     3215                        JSQ Don't Use                0.000000   
1358     3480                         WS Don't Use                0.000000   
1359     3197                         Hs Don't Use               40.719252   

      start station longitude       lat      long  
0                  -73.971146  0.712118 -1.291040  
1                  -73.954847  0.710712 -1.290756  
2                  -73.953517  0.711595 -1.290732  
3                  -73.987140  0.710845 -1.291319  
4                  -73.996010  0.710773 -1.291474  
...                       ...       ...       ...  
1355               -74.010020  0.709919 -1.291719  
1356                 0.000000  0.000000  0.000000  
1357                 0.000000  0.000000  0.000000  
1358                 0.000000  0.000000  0.000000  
1359               -74.034234  0.710685 -1.292141  

[1360 rows x 6 columns]

In [55]:
Distance3 = pd.DataFrame(dist.pairwise(ride_stations_df[['lat','long']].to_numpy())*6373, columns=ride_stations_df.dock_id.unique(), index=ride_stations_df.dock_id.unique())

In [58]:
pd.set_option('display.max_columns', None)

In [68]:
pd.set_option('display.max_rows', None)

In [61]:
Distance3 = Distance3.sort_index()

In [57]:
Distance3.to_csv("../data/distance3.csv")

In [3]:
stations['dock_id'].nunique()

788

In [40]:
stations2 = stations[['dock_id', '_lat', '_long']]

In [41]:
stations2 = stations2.drop_duplicates(subset = ['dock_id'])

In [42]:
stations2['dock_id'] = stations2['dock_id'].astype(str)

In [43]:
stations2.dtypes

dock_id     object
_lat       float64
_long      float64
dtype: object

In [44]:
# Convert the Lat/Long degress in Radians
stations2['_lat'] = np.radians(stations2['_lat'])
stations2['_long'] = np.radians(stations2['_long'])

In [45]:
# Scipy get_metrics()
dist = DistanceMetric.get_metric('manhattan')

In [46]:
stations2[['_lat','_long']].to_numpy()

array([[ 0.71152312, -1.29143769],
       [ 0.71068264, -1.29166001],
       [ 0.71054403, -1.29154653],
       ...,
       [ 0.71177058, -1.29011824],
       [ 0.71229386, -1.29070376],
       [ 0.71218438, -1.29075287]])

In [48]:
dist.pairwise(stations2 [['_lat','_long']].to_numpy())*6373

array([[ 0.        ,  6.77322946,  6.93340042, ...,  9.98588074,
         9.58923515,  8.57848966],
       [ 6.77322946,  0.        ,  1.60660371, ..., 16.7591102 ,
        16.36246462, 15.35171912],
       [ 6.93340042,  1.60660371,  0.        , ..., 16.91928116,
        16.52263558, 15.51189008],
       ...,
       [ 9.98588074, 16.7591102 , 16.91928116, ...,  0.        ,
         7.06643131,  6.68168731],
       [ 9.58923515, 16.36246462, 16.52263558, ...,  7.06643131,
         0.        ,  1.01074549],
       [ 8.57848966, 15.35171912, 15.51189008, ...,  6.68168731,
         1.01074549,  0.        ]])

In [49]:
Distance = pd.DataFrame(dist.pairwise(stations2[['_lat','_long']].to_numpy())*6373, columns=stations2.dock_id.unique(), index=stations2.dock_id.unique())

In [55]:
Distance.to_csv("../Data/distance.csv")

In [50]:
Distance

72         79         82         83        116        119  \
72     0.000000   6.773229   6.933400  11.239997   3.677703   9.685671   
79     6.773229   0.000000   1.606604   7.300459   3.095526   5.746133   
82     6.933400   1.606604   0.000000   5.693855   3.552013   4.139529   
83    11.239997   7.300459   5.693855   0.000000   9.245869   1.554326   
116    3.677703   3.095526   3.552013   9.245869   0.000000   7.691543   
...         ...        ...        ...        ...        ...        ...   
3530  10.100892  16.874122  17.034293  17.424265  13.778596  16.250567   
3531  10.008349  16.781579  16.941750  17.331721  13.686052  16.158024   
3532   9.985881  16.759110  16.919281  17.309253  13.663584  16.135556   
3533   9.589235  16.362465  16.522636  16.912607  13.266938  15.738910   
3534   8.578490  15.351719  15.511890  15.901862  12.256193  14.728165   

            120        127        128       137  ...       3525       3526  \
72    12.808227   5.379408   5.473731  2.964164  ...   9.733055   9.887220   
79     8.868688   1.410950   1.299498  8.481831  ...  16.506285  16.660449   
82     7.262085   3.017554   2.083891  8.642002  ...  16.666456  16.820620   
83     2.222706   8.711409   7.777746  9.031974  ...  17.056428  17.210592   
116   10.814098   1.701705   1.796028  5.386305  ...  13.410759  13.564923   
...         ...        ...        ...       ...  ...        ...        ...   
3530  15.201559  15.480301  15.574624  8.392291  ...   0.367837   0.660594   
3531  15.109016  15.387758  15.482080  8.299748  ...   7.819124   8.279615   
3532  15.086547  15.365289  15.459612  8.277279  ...   0.922874   1.383365   
3533  14.689902  14.968644  15.062966  7.880634  ...   7.989305   8.449797   
3534  13.679156  13.957898  14.052221  6.869888  ...   7.604561   8.065053   

           3527       3528       3529       3530       3531       3532  \
72    10.220909  10.044833  10.497983  10.100892  10.008349   9.985881   
79    16.994139  16.818062  17.271212  16.874122  16.781579  16.759110   
82    17.154310  16.978233  17.431383  17.034293  16.941750  16.919281   
83    17.544282  17.368205  17.821355  17.424265  17.331721  17.309253   
116   13.898613  13.722536  14.175686  13.778596  13.686052  13.663584   
...         ...        ...        ...        ...        ...        ...   
3530   6.167138   1.573235   6.738081   0.000000   7.619021   0.722771   
3531   1.451883   9.192256   0.880940   7.619021   0.000000   6.896250   
3532   5.444367   2.296006   6.015309   0.722771   6.896250   0.000000   
3533   1.622065   9.362438   1.051122   7.789203   0.419114   7.066431   
3534   1.642420   8.977694   1.919493   7.404459   1.429860   6.681687   

           3533       3534  
72     9.589235   8.578490  
79    16.362465  15.351719  
82    16.522636  15.511890  
83    16.912607  15.901862  
116   13.266938  12.256193  
...         ...        ...  
3530   7.789203   7.404459  
3531   0.419114   1.429860  
3532   7.066431   6.681687  
3533   0.000000   1.010745  
3534   1.010745   0.000000  

[788 rows x 788 columns]

In [52]:
stations.dtypes

dock_id          int64
dock_name       object
date            object
hour             int64
minute           int64
avail_bikes      int64
avail_docks      int64
tot_docks        int64
_lat           float64
_long          float64
in_service       int64
status_key      object
dock_status     object
time            object
dayofweek        int64
dayofweek2      object
season          object
dtype: object

In [54]:
stations[stations['dock_id'] == 72]

dock_id         dock_name        date  hour  minute  avail_bikes  \
0              72  W 52 St & 11 Ave  2015-03-01     1       6            8   
1              72  W 52 St & 11 Ave  2015-03-01     1      16            8   
2              72  W 52 St & 11 Ave  2015-03-01     1      25            8   
3              72  W 52 St & 11 Ave  2015-03-01     1      35            8   
4              72  W 52 St & 11 Ave  2015-03-01     1      45            8   
...           ...               ...         ...   ...     ...          ...   
30916806       72  W 52 St & 11 Ave  2019-03-31    16      26           45   
30916807       72  W 52 St & 11 Ave  2019-03-31    17      26           44   
30916808       72  W 52 St & 11 Ave  2019-03-31    18      49           49   
30916809       72  W 52 St & 11 Ave  2019-03-31    20      30           53   
30916810       72  W 52 St & 11 Ave  2019-03-31    24      35           47   

          avail_docks  tot_docks       _lat      _long  in_service status_key  \
0                  31         39  40.767272 -73.993929           1          1   
1                  31         39  40.767272 -73.993929           1          1   
2                  30         38  40.767272 -73.993929           1          1   
3                  30         38  40.767272 -73.993929           1          1   
4                  30         38  40.767272 -73.993929           1          1   
...               ...        ...        ...        ...         ...        ...   
30916806           10         55  40.767272 -73.993929           1          1   
30916807           11         55  40.767272 -73.993929           1          1   
30916808            6         55  40.767272 -73.993929           1          1   
30916809            2         55  40.767272 -73.993929           1          1   
30916810            8         55  40.767272 -73.993929           1          1   

          dock_status   time  dayofweek dayofweek2  season  
0         Empty Alert    1:6          6     Sunday  spring  
1         Empty Alert   1:16          6     Sunday  spring  
2         Empty Alert   1:25          6     Sunday  spring  
3         Empty Alert   1:35          6     Sunday  spring  
4         Empty Alert   1:45          6     Sunday  spring  
...               ...    ...        ...        ...     ...  
30916806   Full Alert  16:26          6     Sunday  spring  
30916807   Full Alert  17:26          6     Sunday  spring  
30916808   Full Alert  18:49          6     Sunday  spring  
30916809   Full Alert  20:30          6     Sunday  spring  
30916810   Full Alert  24:35          6     Sunday  spring  

[11607 rows x 17 columns]